### ISSUE TITLE
missing table blog_post_likes

### ISSUE THREAD

**Issue by bulnv** [ericnanhu/blog#1]
Heya! Wanted to reuse your blog app for my project. But faced some DB or graphQL inconsistency, on many operations like post create or update app crashes with message "blog_post_like" table not found. Just wondering is there migration missing or graphql schemas from another version? thx in advance!

**Comment by ericnanhu** [comment]
Hi, thank you for your interest in my project. But I was not able to recreate the error you are getting. Did you run the migrations? And did you get an error when running the migrations?

**Comment by bulnv** [comment]
Thanks for quick answer! That was my bad, conflict in migrations!
